version: '3.8'

services:
  caddy:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - CADDY_EMAIL=your-email@example.com
      - CADDY_AGREE=true
    depends_on:
      - backend1
      - backend2

  backend1:
    build:
      context: ./backend1
    container_name: backend1

  backend2:
    build:
      context: ./backend2
    container_name: backend2

volumes:
  caddy_data:
  caddy_config:

